source "http://rubygems.org"

gem "sinatra", "~> 1.2.3"
gem "shotgun", "~> 0.9"
gem "haml", "~> 3.1.1"
gem "sass", "~> 3.1.1"
gem "compass", "~> 0.11.5"
gem "ffi"
gem "chunky_png"
gem "fssm"
gem "highline"
gem "meyer-reset"
gem "grid-coordinates", "~> 1.1.4"
gem "meyer-reset"
gem "rb-inotify"
gem "capistrano"
gem "railsless-deploy"
