source "http://rubygems.org"

gem "sinatra",          "~> 1.2.3"
gem "shotgun",          "~> 0.9"
gem "bundler"
gem "haml",             "~> 3.1.1"
gem "sass",             "~> 3.1.1"
gem "compass",          "~> 0.11.5"
gem "ffi",              "~> 1.0.9"
gem "chunky_png",       "~> 1.2.5"
gem "fssm",             "~> 0.2.7"
gem "highline",         "~> 1.6.2"
gem "meyer-reset"
gem "grid-coordinates", "~> 1.1.4"
gem "rb-inotify"
gem "capistrano"
gem "railsless-deploy"
#testt
gem "tilt"
